In [12]:
# cafe_sales.csv 파일을 읽어와서 데이터프레임에 가져오는 코드를 작성하세요
import pandas as pd

df = pd.read_csv("cafe_sales.csv")
print(df)

   order_id        date store   menu category  price  quantity payment
0     A1034  2026-09-01   홍대점   카페라떼       커피   5000         3      카드
1     A1055  2026-09-01   홍대점  치즈케이크      디저트   6500         4      카드
2     A1035  2026-09-02   판교점   콜드브루       커피   5000         1      카드
3     A1048  2026-09-02   판교점  치즈케이크      디저트   6500         3      카드
4     A1059  2026-09-02   판교점    크로플      디저트   5500         2      카드
5     A1003  2026-09-03   강남점  치즈케이크      디저트   6500         1      카드
6     A1011  2026-09-03   홍대점    마들렌      디저트   3000         3    간편결제
7     A1013  2026-09-03   강남점   콜드브루       커피   5000         4      카드
8     A1026  2026-09-03   홍대점  치즈케이크      디저트   6500         4    간편결제
9     A1042  2026-09-03   강남점  아메리카노       커피   4500         1      카드
10    A1008  2026-09-04   홍대점   카페라떼       커피   5000         1      카드
11    A1025  2026-09-05   판교점  바닐라라떼       커피   5500         4    간편결제
12    A1053  2026-09-06   홍대점  치즈케이크      디저트   6500         4      카드
13    A1004  2026-09-07   판교점   콜드브루       커피   5000         1    간편결제
14    A1005  2026-09-07   홍대점    마들렌      디저트   3000         2      현금
15    A1012  2026-09-07   강남점   카페라떼       커피   5000         2      카드
16    A1015  2026-09-07   판교점   녹차라떼      논커피   5500         1    간편결제
17    A1046  2026-09-07   강남점   카페라떼       커피   5000         4      카드
18    A1057  2026-09-07   강남점   녹차라떼      논커피   5500         1    간편결제
19    A1002  2026-09-08   판교점  바닐라라떼       커피   5500         1    간편결제
20    A1022  2026-09-08   판교점    마들렌      디저트   3000         3    간편결제
21    A1040  2026-09-08   강남점   콜드브루       커피   5000         3      카드
22    A1049  2026-09-08   강남점   콜드브루       커피   5000         4      카드
23    A1027  2026-09-09   강남점    마들렌      디저트   3000         1    간편결제
24    A1029  2026-09-10   강남점  치즈케이크      디저트   6500         4      카드
25    A1007  2026-09-11   강남점   녹차라떼      논커피   5500         2      카드
26    A1019  2026-09-13   강남점   녹차라떼      논커피   5500         2    간편결제
27    A1039  2026-09-13   홍대점  딸기스무디      논커피   6000         4      카드
28    A1023  2026-09-14   홍대점  치즈케이크      디저트   6500         2      카드
29    A1047  2026-09-14   홍대점  치즈케이크      디저트   6500         1      카드
30    A1050  2026-09-14   홍대점  바닐라라떼       커피   5500         4      카드
31    A1056  2026-09-14   판교점    마들렌      디저트   3000         4      카드
32    A1014  2026-09-15   강남점  딸기스무디      논커피   6000         3      카드
33    A1017  2026-09-15   홍대점  치즈케이크      디저트   6500         2      카드
34    A1024  2026-09-17   강남점    크로플      디저트   5500         1      카드
35    A1038  2026-09-17   강남점  치즈케이크      디저트   6500         2      카드
36    A1060  2026-09-17   강남점   카페라떼       커피   5000         1    간편결제
37    A1033  2026-09-18   강남점    마들렌      디저트   3000         3      현금
38    A1006  2026-09-19   강남점   녹차라떼      논커피   5500         2      현금
39    A1041  2026-09-19   강남점    마들렌      디저트   3000         2      카드
40    A1045  2026-09-19   강남점    크로플      디저트   5500         4      현금
41    A1032  2026-09-20   강남점   콜드브루       커피   5000         3      카드
42    A1001  2026-09-21   강남점   카페라떼       커피   5000         3      카드
43    A1016  2026-09-21   판교점  바닐라라떼       커피   5500         2      카드
44    A1052  2026-09-21   강남점    마들렌      디저트   3000         1      카드
45    A1037  2026-09-22   판교점    크로플      디저트   5500         2      카드
46    A1044  2026-09-22   강남점    크로플      디저트   5500         2    간편결제
47    A1010  2026-09-24   판교점    크로플      디저트   5500         1      현금
48    A1030  2026-09-24   판교점   녹차라떼      논커피   5500         2    간편결제
49    A1036  2026-09-24   강남점    크로플      디저트   5500         2      카드
50    A1058  2026-09-24   강남점    마들렌      디저트   3000         3      카드
51    A1028  2026-09-25   판교점   녹차라떼      논커피   5500         3      카드
52    A1018  2026-09-27   강남점  아메리카노       커피   4500         1      카드
53    A1009  2026-09-28   판교점  딸기스무디      논커피   6000         3      카드
54    A1043  2026-09-28   강남점  딸기스무디      논커피   6000         2      카드
55    A1051  2026-09-28   홍대점   카페라떼       커피   5000         1      카드
56    A1054  2026-09-28   강남점  치즈케이크      디저트   6500         2      현금
57    A1020  2026-09-29   강남점  딸기스무디      논커피   6000         4      현금
58    A1021  2026-09-29   강남점    크로플      디저트   5500         3      카드
59    A1031  2026-09-30   판교점   카페라떼       커피   5000         3    간편결제

In [13]:
# menu, price의 두열만 선택 한후 앞 3행을 출력하는 코드를 작성하세요.
df[["menu", "price"]].head(3)

    menu  price
0   카페라떼   5000
1  치즈케이크   6500
2   콜드브루   5000

In [14]:
# price의 평균과 최대값을 구하는 코드를 작성하세요.
print(df["price"].mean(), df["price"].max())

5200.0 6500

In [15]:
# quantity의 합계(전체 판매 수량)를 구하는 코드를 작성하세요.
print(df["quantity"].sum())

144

In [21]:
# 매출(sales) 컴럼을 추가
# 가격 X 수량
df["sales"] = df["price"] * df["quantity"]
df.head(5)

  order_id        date store   menu category  price  quantity payment  sales
0    A1034  2026-09-01   홍대점   카페라떼       커피   5000         3      카드  15000
1    A1055  2026-09-01   홍대점  치즈케이크      디저트   6500         4      카드  26000
2    A1035  2026-09-02   판교점   콜드브루       커피   5000         1      카드   5000
3    A1048  2026-09-02   판교점  치즈케이크      디저트   6500         3      카드  19500
4    A1059  2026-09-02   판교점    크로플      디저트   5500         2      카드  11000

In [24]:
# 강남점 주문만 주문 건수와 매출 합계를 구함
gangnam = df[df["store"] == "강남점"]
gangnam.head(5)
print(len(gangnam)) # 주문건수
print(gangnam["sales"].sum()) # 매출 합계

31
376000

In [26]:
# 디저트 중 매출(sales)이 20000 이산인 주문을 출력
print(df[(df["sales"] >= 20000) & (df["category"] == "디저트")])

   order_id        date store   menu category  price  quantity payment  sales
1     A1055  2026-09-01   홍대점  치즈케이크      디저트   6500         4      카드  26000
8     A1026  2026-09-03   홍대점  치즈케이크      디저트   6500         4    간편결제  26000
12    A1053  2026-09-06   홍대점  치즈케이크      디저트   6500         4      카드  26000
24    A1029  2026-09-10   강남점  치즈케이크      디저트   6500         4      카드  26000
40    A1045  2026-09-19   강남점    크로플      디저트   5500         4      현금  22000

In [27]:
# 지점별 매출(sales)를 조회
print(df.groupby("store")["sales"].sum())

store
강남점    376000
판교점    182500
홍대점    196500
Name: sales, dtype: int64

In [28]:
# 매출이 추가된 dataframe을 cafe_sales2.csv로 저장
df.to_csv("cafe_sales2.csv")